version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: pkit
    main: ./cmd/pkit
    binary: pkit
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
      - arm
      - 386
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: freebsd
        goarch: arm
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.buildSource=binaryRelease
    flags:
      - -trimpath

archives:
  - id: pkit-archive
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}32-bit
      {{- else if eq .Arch "arm" }}armv{{ .Arm }}
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  use: github-native
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: whisller
    name: pkit
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
  header: |
    ## pkit v{{.Version}}

    Prompt library manager with CLI and web interface.

    ### Installation

    Download the appropriate archive for your platform below, extract it, and move the `pkit` binary to a directory in your PATH.

    **macOS users:** After downloading, you may need to run:
    ```bash
    xattr -d com.apple.quarantine pkit
    ```

    ### Quick Start

    ```bash
    # Subscribe to a prompt source
    pkit subscribe fabric/patterns

    # Search and browse prompts
    pkit find

    # Start web interface
    pkit serve
    ```
  footer: |
    ---

    **Full Changelog**: https://github.com/whisller/pkit/compare/{{ .PreviousTag }}...{{ .Tag }}

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser)
